language: node_js
node_js:
  - "11"
dist: trusty
addons:
  chrome: stable
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn global add @angular/cli
script:
  - yarn ci-test
  - yarn build
  - yarn codecov -t $CODECOV_TOKEN
